
[Logger]
Greeting   = "Hello there, welcome to the Go Shell"
Salute     = "Later homeboy"
LogFile    = "/tmp/GoShellLogfile.txt"
DtFormat   = "01-02-2006 15:04:05"
DtTimeZone = "UTC -7"
DtOffset   = -7