
[Logger]
Greeting   = "Welcome to the gofsh interactive shell"
Salute     = "Ending gofsh interactive session"
LogFile    = "/tmp/gofshLog.txt"
DtFormat   = "01-02-2006 15:04:05"
DtTimeZone = "UTC -7"
DtOffset   = -7